version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - HOST=${HOST}
      - PORT=${PORT}
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - app-network

  queue_worker:
    build: .
    volumes:
      - .:/app
    command: taskiq worker app.core.services.queue.taskiq.init:broker app.core.tasks
    networks:
      - app-network

  scheduler:
    build: .
    volumes:
      - .:/app
    command: taskiq scheduler app.core.services.queue.taskiq.init:scheduler_taksiq app.core.tasks
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
    networks:
      - app-network

  migrations:
    build: .
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        alembic upgrade head &&
        echo "✅  Миграции успешно применены!"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
    networks:
      - app-network

volumes:
  postgres_data:
  redis-data:

networks:
  app-network:
    driver: bridge
